### ISSUE TITLE
Could you give a step by step on how to run this project?

### ISSUE THREAD

**Issue by chinajinwanjun** [Conflux-Chain/js-conflux-sdk#11]
I can executed some files by cmd "node example.js", but I dont know how to use the frontend file, better if you can provide a step by step document on this sdk.

I am confused on the frontend and backend file because they are similar js.

**Comment by yqrashawn** [comment]
The recommended way to use this sdk in the frontend documented in the `umd` section of the [README.md](https://github.com/Conflux-Chain/js-conflux-sdk#umd) file.

They are the same js just compiled for different targets.
