### ISSUE TITLE
调用合约方法的例子没有

### ISSUE THREAD

**Issue by xiaods** [Conflux-Chain/js-conflux-sdk#111]
范例代码中不详细。
https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/example/4_contract_deploy_and_call.js

请给予提供范例。

**Comment by Pana** [comment]
现在文档中合约交互介绍部分有介绍，之后会继续加强

**Comment by xiaods** [comment]
你没有理解我的处境。我需要通过方法把一个合约的接口函数都遍历出来才行。但是SDK中如何解析一个新建的合约，并把所有public的函数都放到数组里面才行。不然我没法render到页面，让别人调用。

web3js是支持的。

**Comment by xiaods** [comment]
经过沟通，我在验证下。

**Comment by xiaods** [comment]
我又回到这个issue里面：
现在合约已经部署到链上了。现在我需要调用这个远程合约的函数。所以，我会这样操作

	const newContract = conflux.Contract({
								abi: JSON.parse(JSON.stringify([abi])),
								address,
							});

拿到合约实例。
然后，我如何调用这个合约的函数呢？

**Comment by xiaods** [comment]
@Pana  有空看看奥。

**Comment by Pana** [comment]
合约实例化之后，可以直接调用它的相关方法了例如：

newContract.method_name(parameter)

or

newContract[method_name](parameter)

**Comment by Braveheartforyou** [comment]
> 合约实例化之后，可以直接调用它的相关方法了例如：
> 
> ```js
> newContract.method_name(parameter)
> 
> // or
> 
> newContract[method_name](parameter)
> ```

newContract.method_name(parameter)
会报错 Error: Transaction execution failed, data: 0x566d4572726f7228426164496e737472756374696f6e207b20696e737472756374696f6e3a20323235207d29
并且这个错不太好定位
