### ISSUE TITLE
Fail to call overrided function in umd version.

### ISSUE THREAD

**Issue by ChenxingLi** [Conflux-Chain/js-conflux-sdk#118]
I met a bug in the umd version of js-sdk. 

To reproduce this bug, I make a HTML file with the following code first.
```html
<script src="https://cdn.jsdelivr.net/npm/js-conflux-sdk/dist/js-conflux-sdk.umd.min.js"></script>
```

Then I open Chrome console and paste
```javascript
abi=[{"inputs":[{"internalType":"bytes32","name":"_input","type":"bytes32"},{"internalType":"bytes32","name":"_input2","type":"bytes32"}],"name":"hash","outputs":[],"stateMutability":"payable","type":"function","payable":true},{"inputs":[{"internalType":"bytes32","name":"_input","type":"bytes32"}],"name":"hash","outputs":[],"stateMutability":"payable","type":"function","payable":true}];

// It doesn't matter what's address here.
address="cfxtest:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa6f0vrcsw";
provider = new Conflux.Conflux({url: "https://test.confluxrpc.com/"});
contract = provider.Contract({abi,address});

input=Conflux.format.hexBuffer('0x7777777777777777777777777777777777777777777777777777777777777777');
contract.hash(input)
```

Then I got the following errors
```
ContractMethodOverride.js:28 Uncaught Error: can not match override "hash(bytes32,bytes32)|hash(bytes32)" with args (wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww)
    at e.value (ContractMethodOverride.js:28)
    at <anonymous>:9:10
```

**Comment by fgrass** [comment]
It's someone has a solution?

**Comment by GeekBerry** [comment]
> I met a bug in the umd version of js-sdk.
> 
> To reproduce this bug, I make a HTML file with the following code first.
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/js-conflux-sdk/dist/js-conflux-sdk.umd.min.js"></script>
> ```
> 
> Then I open Chrome console and paste
> 
> ```js
> abi=[{"inputs":[{"internalType":"bytes32","name":"_input","type":"bytes32"},{"internalType":"bytes32","name":"_input2","type":"bytes32"}],"name":"hash","outputs":[],"stateMutability":"payable","type":"function","payable":true},{"inputs":[{"internalType":"bytes32","name":"_input","type":"bytes32"}],"name":"hash","outputs":[],"stateMutability":"payable","type":"function","payable":true}];
> 
> // It doesn't matter what's address here.
> address="cfxtest:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa6f0vrcsw";
> provider = new Conflux.Conflux({url: "https://test.confluxrpc.com/"});
> contract = provider.Contract({abi,address});
> 
> input=Conflux.format.hexBuffer('0x7777777777777777777777777777777777777777777777777777777777777777');
> contract.hash(input)
> ```
> 
> Then I got the following errors
> 
> ```
> ContractMethodOverride.js:28 Uncaught Error: can not match override "hash(bytes32,bytes32)|hash(bytes32)" with args (wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww)
>     at e.value (ContractMethodOverride.js:28)
>     at <anonymous>:9:10
> ```
我提交了[一个 PR](https://github.com/Conflux-Chain/js-conflux-sdk/pull/130) 来解决这个问题
