### ISSUE TITLE
Subscriptions are not available on this transport.

### ISSUE THREAD

**Issue by dlgchg** [Conflux-Chain/js-conflux-sdk#121]
use `conflux.subscribeEpochs()` get error
**Subscriptions are not available on this transport.**

all conflux.subscribeXXX... 
all error  **Subscriptions are not available on this transport.**

**Comment by Thegaram** [comment]
You'll need to connect through WebSocket (e.g. `wss://test.confluxrpc.com/ws`, more endpoints [here](https://developer.conflux-chain.org/docs/sdks-and-tools/en/conflux_rpcs)).
