### ISSUE TITLE
address format util not support 0

### ISSUE THREAD

**Issue by 0x74616e67** [Conflux-Chain/js-conflux-sdk#132]
Call format.address('0x17ff0874d9d9df8b26ea7f80e826399b65a1462f', 0) will throw an error, such as:
Invalid address format: path="", h(0x17ff0874d9d9df8b26ea7f80e826399b65a1462f,0), expected parameter: networkId

**Comment by Pana** [comment]
The next version will support

**Comment by Pana** [comment]
1.6.10 support this
