### ISSUE TITLE
How to get return value of transaction calls

### ISSUE THREAD

**Issue by bianyuanop** [Conflux-Chain/js-conflux-sdk#157]
abi: https://file.io/sIPB4teGXDof
delpoyed contract address: cfxtest:acc8ctvggnkksv4g2t3zcae2zs6m32nfv6dn9xt77n
My code:
```
const cfx = new Conflux({
  url: 'https://test.confluxrpc.com',
  networkId: 1,
});

const contract = cfx.Contract({abi, address:'cfxtest:acc8ctvggnkksv4g2t3zcae2zs6m32nfv6dn9xt77n'});
const account = cfx.wallet.addPrivateKey(privateKeys.producer);

const res = await contract.produce("Test1", "Describe1", "loctaion1", "Event1").sendTransaction({from: account}).executed();
console.log(res);
``` in a function

output: ```
{
  transactionHash: '0xb1f66c4d70717f96ee066236253f0fe5ca19895e03ddbb62df3e5df4319064b3',
  index: 0,
  blockHash: '0xe19349506ce2fd8c8a5492098a3a76af1047816dd3c24c6bf56d276d998f5d70',
  epochNumber: 52220907,
  from: 'cfxtest:aamk788rnbp7yev8yxc7mz4xjfx7c3ygup4bsm06kr',
  to: 'cfxtest:acc8ctvggnkksv4g2t3zcae2zs6m32nfv6dn9xt77n',
  gasUsed: 72056n,
  gasFee: 72056n,
  contractCreated: null,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  stateRoot: '0xdd77b8133070d4f3787a3db97baade81f4069e2a12427336d7541732add93ce9',
  outcomeStatus: 0,
  txExecErrorMsg: null,
  gasCoveredBySponsor: false,
  storageCoveredBySponsor: false,
  storageCollateralized: 448n,
  storageReleased: []
}
```
as my understanding of the doc, the output of the transaction call result should be placed at `receipt.logs` and then i can use `contract.abi.decodeLog` to decode it, but why my transaction output contains no log?

**Comment by bianyuanop** [comment]
shortcut of produce function abi: ```
{
      "inputs": [
        {
          "internalType": "string",
          "name": "name",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "describe",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "loc",
          "type": "string"
        },
        {
          "internalType": "string",
          "name": "ev",
          "type": "string"
        }
      ],
      "name": "produce",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
```

**Comment by Thegaram** [comment]
You cannot directly get the return value from a transaction. You have two options:

- Make a call instead of a transaction (`.call`). This will execute the transaction and return the result without modifying the state on the blockchain. This can be problematic if you do want to change the state: the result between a `call` and a `sentTransaction` might change.
- In your function, emit an event with the value you want to read. Then it will show up in the receipts and you can decode it.

**Comment by bianyuanop** [comment]
Thank u for answering 

> You cannot directly get the return value from a transaction. You have two options:
> 
> * Make a call instead of a transaction (`.call`). This will execute the transaction and return the result without modifying the state on the blockchain. This can be problematic if you do want to change the state: the result between a `call` and a `sentTransaction` might change.
> * In your function, emit an event with the value you want to read. Then it will show up in the receipts and you can decode it.
