### ISSUE TITLE
No API to create account by mnemonic

### ISSUE THREAD

**Issue by withgogo** [Conflux-Chain/js-conflux-sdk#210]
I didn't find any method to create account by mnemonic

**Comment by Thegaram** [comment]
I think we can consider adding this feature @Pana.

In the meantime, you can use other libraries to derive the private keys, then import them into `js-conflux-sdk`, e.g.

```js
const ethers = require('ethers');
const node = await ethers.utils.HDNode.fromMnemonic('***');
const account0 = node.derivePath("m/44'/503'/0'/0/0");
const account1 = node.derivePath("m/44'/503'/0'/0/1");
// ...
```

**Comment by Geoge1** [comment]
> I didn't find any method to create account by mnemonic

Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by Pana** [comment]
Ok, we will add this feature

**Comment by Pana** [comment]
Check this https://github.com/Conflux-Chain/js-conflux-sdk/blob/v2/docs/account.md#hd-wallet
