### ISSUE TITLE
the method cfx_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by paschal533** [Conflux-Chain/js-conflux-sdk#211]
Hello
I tried to call this function from the smart contract I deployed to conflux testnet,

`const transaction = await Contract.create( name ).sendTransaction({ from: me.address, gasPrice: 10000000 }).executed();`

but It is returning
this error `Error: the method cfx_sendTransaction does not exist/is not available`

**Comment by Thegaram** [comment]
Hi, did you follow this guide? https://docs.confluxnetwork.org/js-conflux-sdk/docs/interact_with_contract#how-to-get-and-update-contracts-state

Are you using a local wallet (import private key) or Fluent as your provider?

**Comment by paschal533** [comment]
I imported a private key. Do I have to deploy the abi and the bytecode, after migrating the smart contract with cfxtruffle? Because according to the documentation you sent, they deployed the abi and the bytecode

**Comment by Pana** [comment]
You can check this https://github.com/Conflux-Chain/js-conflux-sdk/blob/v2/docs/error_handling.md#method-not-found

**Comment by 2022canglang** [comment]
请问，调用合约setApprovalForAll的sendTransaction函数，返回错误RPCError: the method cfx_sendTransaction does not exist/is not available , (调用时是导入了私钥的)。没有找到原因，求助求助。
