### ISSUE TITLE
关于返回错误RPCError: the method cfx_sendTransaction does not exist/is not available的问题

### ISSUE THREAD

**Issue by 2022canglang** [Conflux-Chain/js-conflux-sdk#229]
请问，调用合约setApprovalForAll的sendTransaction函数，返回错误RPCError: the method cfx_sendTransaction does not exist/is not available , (调用时是导入了私钥的)。没有找到原因，求助求助。

**Comment by zhbyak** [comment]
遇到类似的问题：Unsupported Method: cfx_call
感觉是某个时序不太对，因为如果再等一段时间，再调用`await contract.totalSupply();`方法 就不会出这个问题了

**Comment by zhbyak** [comment]
遇到类似的问题：Unsupported Method: cfx_call
感觉是某个时序不太对，因为如果再等一段时间，再调用`await contract.totalSupply();`方法 就不会出这个问题了

**Comment by Pana** [comment]
此问题应该是没有往 wallet 添加私钥，或者发送交易的 from 与私钥账户不对应导致的
