### ISSUE TITLE
发生了VmError(BadInstruction { instruction: 248 })错误

### ISSUE THREAD

**Issue by 0xSing** [Conflux-Chain/js-conflux-sdk#230]
我在前端使用js-conflux-sdk的方法调用一个已经部署在test网上的合约时
发生了VmError(BadInstruction { instruction: 248 })错误

我只能在网上查询到一个类似错误VmError(BadInstruction { instruction: 238 })为合约部署错误
但是合约能在conflux studio中成功调用

如果有清楚的朋友，请告诉我instruction: 248是什么原因造成的
十分感谢

**Comment by Pana** [comment]
此错误大概率为调用合约时，没有正确设置合约地址（合约地址为空）导致的
