### ISSUE TITLE
使用js-conflux-sdk的疑问

### ISSUE THREAD

**Issue by xiaozhu001** [Conflux-Chain/js-conflux-sdk#25]

**Comment by xiaozhu001** [comment]
想问下开发团队contract.method(),返回值是jsbi数据，每次使用数据时都要进行util.unit.fromDripToCFX(balance)转换请问是出于什么原因的考虑？这样对于社区开发者来说很不友好

**Comment by yqrashawn** [comment]
@resodo @GeekBerry 需要回复一下

**Comment by GeekBerry** [comment]
*想问下开发团队contract.method(),返回值是JSBI数据*
是的,用大整数记录金额值, 为兼容前端使用, 采用 JSBI 库.

*转换请问是出于什么原因的考虑*
返回值默认是 Drip, 为值计量最小单位, `fromDripToCFX` 不是必须的, 看使用者得业务需求.

*为什么不返回字符串*
返回 JSBI, 有利于利用 JSBI 库运算函数进一步进行计算.

*这样对于社区开发者来说很不友好*
有什么好的建议, 希望给出使用场景和期望的解决方案

**Comment by resodo** [comment]
返回drip可以保证每次返回的都是整数，没有浮点数可能带来的处理麻烦和精度误差。
比如参考ethereum的rpc或者web3.js，返回的也都是整数而不是浮点数。
我们认为这是面向开发更加友好的方式。
