### ISSUE TITLE
Suggestions for better error message for util sign ecdsaRecover

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/js-conflux-sdk#3]
```js
import {util, Message} 'js-conflux-sdk/dist/js-conflux-sdk.umd.min.js';

util.sign.ecdsaRecover(
  Buffer.from('hello', 'utf8'),
  new Message({
    signature:
    '0x6e913e2b76459f19ebd269b82b51a70e912e909b2f5c002312efc27bcc280f3c29134d382aad0dbd3f0ccc9f0eb8f1dbe3f90141d81574ebb6504156b0d7b95f01'
  })
);
```
The error message is
![image](https://user-images.githubusercontent.com/15090582/74082367-22578e00-4a94-11ea-9f71-80ddde3ab778.png)
which is thrown by `Buffer.concat` [here](https://github.com/Conflux-Chain/js-conflux-sdk/blob/f49400f6071cdb515e45b71396117322c0f7a877/src/util/sign.js#L176), which is not helpful.

The `r` and `s` in `Message` instance are string not buffer. Maybe we should check these values before applying them. Or maybe just support string here.

**Comment by GeekBerry** [comment]
do not use like this:

**Comment by GeekBerry** [comment]
Or you could get PublicKey by method named [message.recover()](https://github.com/Conflux-Chain/js-conflux-sdk/blob/734027551bf33c7dce0247fe900df3fe73311c18/src/Message.js#L109) over v0.7.3

**Comment by yqrashawn** [comment]
I got the idea. The point here is that users aren't able to figure out what's going wrong until they go into `js-conflux-sdk`'s code and see the `Buffer.concat` function. Something like "r must be a buffer" will be really helpful for users to debug their own code.

**Comment by resodo** [comment]
@yqrashawn we are planning to redesign the message sign interfaces. I'm going to close this issue for now.
