### ISSUE TITLE
the util func is ugly for expose

### ISSUE THREAD

**Issue by xiaods** [Conflux-Chain/js-conflux-sdk#30]
I am from conflux-remix project, I use js-conflux-sdk lib as dependencies lib. I need use util's useful func.
But i found the expose name is ugly. 

```
export { util };
```
please consider rename it asap. thanks.

https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/src/index.js#L3

**Comment by GeekBerry** [comment]
ugly 是指? 会带来什么麻烦? 有什么好的建议吗?

**Comment by xiaods** [comment]
util是很常见的变量名，既然暴露出来，就应该考虑被别人引用的情况，在这样的场景下，你会发现它这个暴露的名字很丑的设计。

1、还容易在第三方代码中和其它同样命名的变量重名冲突。
2、util首字母小写，其它Account都是首字母大写，变量大小写规则不一致。

**Comment by GeekBerry** [comment]
非常感谢你的建议, 最近我们将作手升级 js-conflux-sdk 以添加新功能和兼容nodejs使用. 
请问你主要是什么情况下使用sdk? 浏览器还是nodejs? 
在 sdk 兼容和打包方面的问题, 希望也能得到建议和帮助.

**Comment by xiaods** [comment]
我是conflux-remix的社区开发者，我需要帮助conflux维护remix插件，这个插件是用来与公链Conflux 交互的，依赖js-conflux-sdk。
