### ISSUE TITLE
0.9.2版本deploy失败

### ISSUE THREAD

**Issue by calmlism** [Conflux-Chain/js-conflux-sdk#31]
使用节点：http://mainnet-jsonrpc.conflux-chain.org:12537
defaultGasPrice: 1
defaultGas: 1000000

部署合约失败。出现错误RPCError: Invalid parameters: tx
defaultGasPrice改为100，问题依在。

**Comment by GeekBerry** [comment]
有更详细的错误信息吗

**Comment by calmlism** [comment]
Object {data: Object, result: "0x3", duration: 110}
HttpProvider.js:47
Object {data: Object, result: Object, duration: 75}
HttpProvider.js:47
Object {data: Object, result: "0x5943c", duration: 49}
HttpProvider.js:47
Object {data: Object, error: Object, duration: 74}
HttpProvider.js:44
无调试适配器，无法发送"variables"
RPCError: Invalid parameters: tx
deploy.js:35
无调试适配器，无法发送"variables"

输出日志就这些内容。合约之前部署过多次都是可以的，应该可以排除合约的问题。

**Comment by GeekBerry** [comment]
RPCError: Invalid parameters: tx
这个 tx 传的是啥?

**Comment by calmlism** [comment]
里面tx是什么，应该是sdk自己封装的
const contract = cfx.Contract({
    abi: require('./build/CRC721.abi.json'),
    bytecode: require('./build/CRC721.code.json')
  });
const contractinfo = await contract.constructor('Sh','SH')
    .sendTransaction({
      from: account,
      gas: 100000000
    
    })
    .confirmed();

**Comment by resodo** [comment]
建议把复现的文件上传一下，包括json，bytecode和脚本。

**Comment by calmlism** [comment]
解决了，是钱包地址，在vm池中一直存在交易，换了个地址私钥就可以了。
