### ISSUE TITLE
Better to use the current balance to conservatively calculate the storage limit by default than using the estimate

### ISSUE THREAD

**Issue by fanlong** [Conflux-Chain/js-conflux-sdk#33]
The estimate may run differently than the actually execution (for example more zero bytes). And the actually transaction will run out of storage limit.

**Comment by resodo** [comment]
From my thought, maybe a user needs three options to fill in the storage limit:
1. exactly estimate the result
2. estimate result * (1+eps set by user), capped by the current balance
3. conservatively capped by the current balance
Maybe the third one could be a default option.
