### ISSUE TITLE
部署合约碰到的一种情况。

### ISSUE THREAD

**Issue by calmlism** [Conflux-Chain/js-conflux-sdk#34]
在测试部署合约，与钱包转账等复杂的操作下，卡交易总会复现。会出现有的交易哈希是会一直处于打包状态。要么是使用sdk部署合约再也部署不上去了，那么就是web钱包转账就不行了。有时候连接节点部署合约，会出现一直在握手发包的连续状态，就是部署不上去。之后web钱包转账也不好使。有时候是，部署失败提示tx错误之后，使用web钱包发送一笔高费用的交易，之后部署合约就可以部署上了。
网络：pontus网络
尝试使用过的rpc节点：
http://mainnet-jsonrpc.conflux-chain.org:12537
http://52.175.52.111:12537
http://13.67.73.51:12537

地址：0x1fc46011b87442d6a2f25e2e48101cdc9019839b
当前钱包地址的状态：不能部署合约，不能发送交易。
部署合约使用sdk：js-conflux-sdk，0.9.2
出现一直打包状态的hash：
http://confluxscan.io/transactionsdetail/0xf1c029174db948616273c7026c0d2d3a15ccd8fb37ff61e7fc53d522c2a483fc
时间：2020.5.28 20:22

该问题，不是个例，已经三个人反应都碰到过此类情况。
不知是sdk问题还是rust底层问题，都先发issues，进行记录。

**Comment by GeekBerry** [comment]
请问解决了吗, 看起来像 fullnode 的问题.

**Comment by Pana** [comment]
我在本地节点也遇到过类似问题，交易提交了，但一直未被打包，在txPool 里

**Comment by GeekBerry** [comment]
看来不是 sdk 的问题, 应该是 fullnode 节点交易池的 nonce 管理的问题
