### ISSUE TITLE
查询日志不知道怎么用？

### ISSUE THREAD

**Issue by xiaozhu001** [Conflux-Chain/js-conflux-sdk#37]
请问下面的topics 如何得到
![image](https://user-images.githubusercontent.com/31197436/83731489-30ea3680-a67d-11ea-9b35-e5dc0ccc5c19.png)

**Comment by xiaozhu001** [comment]
我找了上下文，都不知道这个hash如何生成，是否可以提供一个demo

**Comment by GeekBerry** [comment]
这里的 topic 是一系列 sha3 的结果, 具体生成方式由 solidity 语言[规范](https://solidity.readthedocs.io/en/v0.5.13/abi-spec.html#events)中规定.

**Comment by GeekBerry** [comment]
如果不想手动去生成topic, 可以参考[示例代码](https://github.com/Conflux-Chain/js-conflux-sdk/blob/4877ba1d4a42aa3a1029039c5599d28ab6878841/example/code/method.js#L84).

例子中查询了 从 `1366360` epoch 起所有 名为 `Event` 且第一个参数是 account (的 address) 的 log.
具体 `Event` 参数结构, 参考 [sodility.sol](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/example/contract/solidity.sol) 文件中定义
