### ISSUE TITLE
最近是有大的更新吗？

### ISSUE THREAD

**Issue by xiaozhu001** [Conflux-Chain/js-conflux-sdk#39]
我在使用0.9.2 版本的js-sdk进行部署智能合约时，现在部署不上去，卡在部署那一步

**Comment by GeekBerry** [comment]
有更新, 现在 confirmed 的条件 transaction 所在 block 被 revert 的概率首次小于等于 1e-8.
现在主网 confirmed 时间大概在 60s, 所以需要等一下.

如果对 confirmed 不是特别在意, 可以改为 await sendTransaction().executed() 即可
