### ISSUE TITLE
What is `format.estimateTx`?

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/js-conflux-sdk#54]
https://github.com/Conflux-Chain/js-conflux-sdk/blob/40da1641bacd7a621a38cec6d8d00da6bf15d563/api.md#L959

**Comment by GeekBerry** [comment]
https://github.com/Conflux-Chain/js-conflux-sdk/blob/40da1641bacd7a621a38cec6d8d00da6bf15d563/src/util/format.js#L433
