### ISSUE TITLE
use JSDoc feature to add links to and examples for

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/js-conflux-sdk#55]
JSDoc has [`namepaths`](https://jsdoc.app/about-namepaths.html) and [`@see`](https://jsdoc.app/tags-see.html) features.

We can combine this with `@example` to generate another `format.md` doc and automatically link `api.md` to `format.md`.

**Comment by GeekBerry** [comment]
already add some link like `[format.sendTx](#util/format.js/epochNumber)`
