### ISSUE TITLE
建议-地址应自动 checkSum 格式化和校验

### ISSUE THREAD

**Issue by ysqi** [Conflux-Chain/js-conflux-sdk#56]
基于我过往的公链开发经验，建议 SDK 和 钱包都能自动对地址进行 checksum 格式化和校验。

以太坊 [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) 有提出建议对地址加入校验码。

含有校验码的地址，能够有效消除用户输入有误等原因输入错误的地址，而导致经济损失的风险。因此，建议 Conflux 能在生态发展之初，就应该在重要生态基础设施中对地址支持 checksum 。

当然，我并没有测试是否SDK已经支持了 checksum ，但我在浏览器中有看到一个尚未含校验码的地址：https://confluxscan.io/address/0x122a43e8da4389377838f62dbb95d94c9fdc210a。

在生态发展之初加入 checksum 的好处有如下几点：

1.  消除 Conflux 和  SDK 间的差已。
2. 从根源上是地址原生具有校验码。
3. 指导 SDK 和生态默认开启地址校验功能。
4. 帮助用户降低可能的经济损失，并消除用户对校验码格式化概念。

**Comment by GeekBerry** [comment]
目前:
* 浏览器中返回的地址为 fullnode 直接获取的返回值, 均为小写hex.
* SDK 并未对地址进行 checksum 检查, 将 address 一律转为小写处理
* 但是 SDK 实现并导出了一个 checksumAddress 函数将地址转为 checksum 地址
https://github.com/Conflux-Chain/js-conflux-sdk/blob/40da1641bacd7a621a38cec6d8d00da6bf15d563/src/util/sign.js#L32
暂时的想法是让有需求的开发者在自己的 app 中自行定义进行 checksum 检查的时机, 并调用 SDK 提供方法自行进行地址对比.

至于是否从SDK层面强制要求必须使用 checksum 地址, 以及其中的利弊, 我们会认真考虑和权衡

**Comment by ysqi** [comment]
> SDK 并未对地址进行 checksum 检查, 将 address 一律转为小写处理

不清楚为何需要转小写。既然有统一转小写，那么应该改成一律转 checksumAddress。

 >至于是否从SDK层面强制要求必须使用 checksum 地址

校验不需要强制，由DAPP自行决定是合理的。但是只有在所有地址的入口处完成转 checksumAddress ，才能为开发者强制校验做准备。

**Comment by GeekBerry** [comment]
完全要求 checksum 看起来这是个长期的工作, 需要 node 和 sdk 都去处理.
也希望您能去 conflux-rust 添加这个 issue.

**Comment by GeekBerry** [comment]
* SDK > v1.0.0 对 address 校验采用和 web3 相同的策略, 对于大小写混合的地址, 将进行 checksum 检查, 全大/小写的地址直接转小写.
* 至于输出地址, 根据 [RSKIP60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md) 规范将于chainId 有关, SDK 暂不输出 checksum 地址, 用户如有需要可以用 sign.checksumAddress 函数进行生成
