### ISSUE TITLE
Some recommendations 

### ISSUE THREAD

**Issue by ysqi** [Conflux-Chain/js-conflux-sdk#67]
小小的总结下：

1. SDK Demo中既然突出了手工调用 estimateGasAndCollateral 设置gasLimit，同样也应该设置 storageCollateralized 。否则新开发者容易忽略stroageLimit，毕竟这是 conflux的特产。
2. estimateGasAndCollateral 如果执行失败，应该抛错，目前是忽略了错误信息（违背常理），处理方式应该同 sendTransaction 遇到 revert 错误处理一样。 模拟的目的除了预估gas，还有是帮助开发者检查交易错误。比如抢购某商品，如果预估时已知道是已抢空，那么用户是不需要还继续发交易的。
3. bytes 和 string 的编码解码需要区别对待，可以研究下 etherjs 
4.  交易的 from 参数可以是 account，用着就害怕，担心是不是要传递私钥啊....，可参考 etherjs
5.  等等交易 confirmed 过程是一个秒级定时器，这个需要优化成订阅模式，由node主动报告状态。如果出现一个火爆的DAPP，这个 DAPP的通信节点不瘫痪才怪。
6. 建议SDK文档中，独立描述公共信息，如 block，Transaction，Receipt等公共信息，这样每种语言SDK就只需要引用就行，还能保持一致性。比如我发送交易需要送什么参数，全靠看Example，而非文档描述（https://developer.conflux-chain.org/docs/js-conflux-sdk/javascript_sdk#confluxprototypesendtransaction）。
7.  SDK 文档中的字段描述，是反人类的。是反着写的：`string` blockHash: Hash of the block where this transaction was in and got executed. 应该改成：`blockHash` (hex): Hash of the block where this transaction was in and got executed。

**Comment by GeekBerry** [comment]
对于附加域, 单独的 estimateGasAndCollateral  不填, 只在发送交易中的estimateGasAndCollateral之前会给默认值

**Comment by GeekBerry** [comment]
- [x]  1. 在 1.x 分支的 [example](https://github.com/Conflux-Chain/js-conflux-sdk/tree/v1.x#send-transaction-complete)中展示了该例子.
- [x] 2. 因为默认参数的不同 estimateGasAndCollateral 有可能和实际发送交易的情况不同, 目前设计时 estimateGasAndCollateral  用于估算值, cfx_call 用于模拟交易并获取错误信息. 至于以后是否会将两者合并, rust 组会考虑.
- [x] 3. bytes 对应 js 中的 Buffer, string 对应 js 中的 String. 目前 string 可能会自动转为 buffer, 比如 `method(bytes arg)` 中传入字符串 "abc" 会自动转为 ascii 码. 同理传入 "0xab" 也会转为 ascii
- [x] 4. sdk 1.0 以上版本将 from 传入 account 的设计取消, 转为由 account 来 sendTransaction, 从而避免看似传递 privateKey 的结构.
- [ ] 5. fullnode 和 jsdk 已经提供 websocket 的交互方式, 但 ws 端口没有对外公开, sdk 短时任然会轮询
- [ ] 6. 我们近期会对 fullnode 和 js sdk, java sdk, go sdk 的接口进行统一, 届时能更好的展示这个问题
- [x] 7. 在新文档中已经修改

**Comment by GeekBerry** [comment]
- [x] 5. SDK 已提供 websocket 交互方式, 但由于 fullnode 短期内不会提供交易状态变化订阅, 因此 SDK 仍然将采用轮询方式获取交易状态.
- [x] 6. 各 SDK 数据均采用 [JSON-RPC](https://developer.conflux-chain.org/docs/conflux-doc/docs/json_rpc) 返回值. 具体参数和返回值请参考上述文档
