### ISSUE TITLE
estimate error: contractAddressConflict

### ISSUE THREAD

**Issue by Pana** [Conflux-Chain/js-conflux-sdk#70]
estimate 的时候现在没有帮用户填写 nonce 等默认值，所以如果用户的第一笔交易是部署合约，之后再部署就会遇到 contractAddressConflict 的问题，本质原因是 fullnode nonce 默认使用了 0，
这个issue 短期应该在 sdk 处理么？
当然长期来看应该由fullnode 提供默认值包括 nonce,gas,gasPrice, storageLimit 等值

**Comment by GeekBerry** [comment]
对于附加域, 单独的 estimateGasAndCollateral 不填, 只在发送交易中的estimateGasAndCollateral之前会给默认值.

**Comment by GeekBerry** [comment]
estimate 只应该用于获取 gas, nonce 在发送交易时会填上, 至于 fullnode 中 cfx_estimateGasAndCollateral 对于 nonce 的要求, sdk 应该保持一致, 同理 cfx_call 和 cfx_sendTransaction 都不再去补充对应域
