### ISSUE TITLE
error .mined function error

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/js-conflux-sdk#78]
The original issue can be found at https://github.com/Conflux-Chain/conflux-portal/issues/207

I reproduced it by deploying a erc-20 token with 0.13.4, the original issue is using 0.13.3.

Error is thrown here

![image](https://user-images.githubusercontent.com/15090582/91678541-69b08380-eb78-11ea-8b53-7bb69e3c8518.png)

```
{"msg":"(NaN not match uint) && (undefined not equal null)","path":".status","origin":{"blockHash":null,"blockNumber":null,"from":"0x11f9bf8b33ad36e34b36184f482ce8eef476e5dc","gas":"0x1c5278","gasPrice":"0x3b9aca00","hash":"0x...","input":"0x..."
```

Expect not to throw.
Expect the error message to be `transactionIndex is NaN not match uint, status is undefined not equal null`

**Comment by GeekBerry** [comment]
为什么 `status` 是 undefined 而非 null ? 有完整的交易信息吗?
