### ISSUE TITLE
Keep master up-to-date with latest release

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/js-conflux-sdk#79]
When people open this repo (and look at master), they see an outdate version of this SDK. It seems like there has been some breaking changes recently, so the examples on master do not work anymore. I suggest we try to keep master in sync with the latest release to avoid confusion.

**Comment by Pana** [comment]
Yes, the alpha version have some breaking change, after discussion we think this is aggressive we will propose a new 1.0 version, currently the npm default version has set to 0.13
