### ISSUE TITLE
Add more helpful error messsages

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Chain/js-conflux-sdk#80]
Recently, a developer ran one of the outdated examples and saw the error [`Invalid account options`](https://github.com/Conflux-Chain/js-conflux-sdk/blob/35f19465c466b8eb30982f551f918a647c352109/src/account/index.js#L57). It would be nice if we could make errors from this module more helpful, e.g. in this case we could warn the caller that the constructor of `Account` expects on objects with either a private key or keystore information.

**Comment by GeekBerry** [comment]
conflux.Account 调用了 [accountFactory](https://github.com/Conflux-Chain/js-conflux-sdk/blob/084527dab64f2fbfecc2f7b13a5ae6b6e1943043/src/account/index.js#L44-L44) 

* 下一版, 本会对错误信息加以细化
* 目前, 用例可以查看文档
* 此外, 该工厂方法能接收多种 options 组合, 如果把组合类型写入错误信息, 在 accountFactory 扩展时还得保证错误信息与逻辑的同步更新

**Comment by Thegaram** [comment]
> 目前, 用例可以查看文档

fyi both the [official docs](https://developer.conflux-chain.org/docs/js-conflux-sdk/javascript_sdk/#accountprototypeconstructor) and the docs [linked on npm](https://github.com/Conflux-Chain/js-conflux-sdk/blob/master/api.md#accountprototypeconstructor-) are outdated.

**Comment by GeekBerry** [comment]
额, 目前 official docs 用的是 master 分支即 v0.13.4 的文档
而该改动为 v1.x 分支即 v1.0.0-alpha.4 的文档.
因为 v1.x 没有正式发版, 暂时 official docs 没有更新, 
至于 npm 链接下一版应该及时更新
thanks

**Comment by GeekBerry** [comment]
sdk 已经更新到 v1.0.0.
创建 account 方式以及错误信息可以参考 [master 分支文档](https://github.com/Conflux-Chain/js-conflux-sdk)
