### ISSUE TITLE
Move @babel/runtime from dependencies to devDependencies

### ISSUE THREAD

**Issue by Pana** [Conflux-Chain/js-conflux-sdk#99]
Seem babel is only used to build front end package, could we move it to devDependencies

"dependencies": {
    "@babel/runtime": "^7.8.4",
    "big.js": "^5.2.2",
    "keccak": "^2.0.0",
    "lodash": "^4.17.19",
    "scrypt-js": "^3.0.1",
    "secp256k1": "^3.7.1",
    "superagent": "^5.1.0",
    "websocket": "^1.0.31"
  }

**Comment by GeekBerry** [comment]
前端打包的相关内容需要咨询前端工程师, 不过既然叫 runtime 更改更要充分研究
